### ISSUE TITLE
Question: Why don't you make it as a wrapper around the linux ext4 codebase?

### ISSUE THREAD

**Issue by VasiliPupkin256** [bobranten/Ext4Fsd#1]
Isn't it easier and straightforward to just wrap a canonical ext4 implementation, provide an underlying block device interface and filesystem entrypoint above, instead of implementing all the features from scratch?

**Comment by bobranten** [comment]
On Fri, 15 May 2020, VasiliPupkin256 wrote:

> Isn't it easier and straightforward to just wrap a canonical ext4 implementation, provide an underlying block device interface and filesystem entrypoint above, instead of implementing all the features from scratch?

You are right that we should try to share as much code as possible, but we 
have already managed to borrow some of the code needed from Linux with 
only small changes to use it on Windows for example the functions to 
access extents and the htree and checksum functions.

Bo Branten
