### ISSUE TITLE
Linux hfsplus vs. OSX HFS+

### ISSUE THREAD

**Issue by juanpc2018** [bobranten/Ext4Fsd#11]
i have a M.2 drive with PCIe_x4 adapter from Startech...
https://www.startech.com/en-us/hdd/pex4m2e1

1 partition was formatted as hfsplus, with hfsplus-tools in Kubuntu 20.10 or pearOS 12.0 "KDE Debian"
but partition is Not detected by Ext2Fs 0.69

partition is detected by Windows8.1x64 Disk Manager as Unallocated.

Strange thing is that i have other HDDs, formatted as HFS+ in real OSX,
and is detected OK by Ext2Fsd 0.69 and Windows8.1 + Bootcamp.

there is something strange about Linux hfsplus that Ext2Fsd & Windows/Bootcamp does Not detect, 
Windows detects as Unallocated.
Ext2fsb does Not detect, Nada, 0, Nothing.

but works Ok in Linux,
also works Ok in OSX HighSierra.

Apple released hfs+ and Apfs as Open source,
Linux version is a translation from OSX to Debian.

Linux partitions ext4 are detected as Linux,
Linux hfsplus, Not detected in Windows.

Ext2fsb does Not detect 
Linux hfsplus is incomplete, does Not allow to change Label Names.
but Linux hfsplus label can be changed in OSX.

**Comment by bobranten** [comment]
Note that the file system type column in the Ext2Mgr is only informative. The Ext2Fsd driver only supports the ext2, ext3 and ext4 file system.
