### ISSUE TITLE
Web page install is confusing

### ISSUE THREAD

**Issue by juanpc2018** [bobranten/Ext4Fsd#12]
http://www.acc.umu.se/~bosse/

 Ext4 filesystem driver for Windows
Release 0.70 beta 3 (2021-02-02)
I am helping Matt Wu to develop support for the new features metadata checksums and 64-bit block numbers in the ext2fsd project. 
If you want to help to test this work here is an install program for the new driver **Ext2Fsd-0.70b3w10-setup.exe for Windows 8 - Windows 10** and Ext2Fsd-0.70b3xp-setup.exe for Windows XP - Windows 7. 

You can also do a manual install over an old release by following these steps: 
1. Install the old driver using the oficial installation program from ext2fsd.com mirrored here. 
2. Copy the new driver (for 32-bit Windows 10 or for 64-bit Windows 10 and for 32-bit Windows XP-8.1 or for **64-bit Windows XP-8.1)** over the old in \windows\system32\drivers. 
3. Reboot. Now you can read and write ext4 filesystems using the latest features from Windows. (sorry I cant sign drivers so you have to turn of Windows checking for that during testing)

Note: The drivers are testsigned, you can allow Windows to load testsigned drivers with the command "bcdedit /set testsigning on".
Source code: https://github.com/bobranten/Ext4Fsd
Official site: Ext2Fsd Project

-----
W10 Installer has 8.1 drivers..
but XP driver has 8.1 ????

problem: i have W8.1x64 and will never buy W10.
W8.1 is far superior.
https://youtu.be/z7Qr6tAh1ag?t=199

**Comment by kenshub** [comment]
I was trying to install directly from GitHub without going to the web page. This helped me get it working.

See also issue #19

**Comment by bobranten** [comment]
We have now done a new release 0.71 that has a signed installation program, it is available both on https://www.accum.se/~bosse/ and on the release tab on GitHub.
