### ISSUE TITLE
imposible to recover a damaged Magic Number SuperBlock

### ISSUE THREAD

**Issue by juanpc2018** [bobranten/Ext4Fsd#13]
i´ve tested everything...
seems NVMe M.2 + PCIe adapter have something different, 
NVMe driver is incomplete vs. Sata-III, or...
e2fsck has Not been updated for NVMe or something..

i did confirmed SuperBlocks available, 
and Backup SuperBlock.
then run:
$ e2fsck -y -b ##### /dev(nvme0n1p#

part is detected with backup SuperBlock, but
does Not repair, probably because the bad Magic number checksum, or something.. 

BusyBox
Grub 
rEFInd
initramfs
Gparted Live USB
No success.

$ fsck
$ e2fsck
$ fsck.ext4

$ lsblk

$ sudo passwd root
$ su

$ mkdir /mnt/mydrive
$ mount /dev/nvme0n1p# /mnt/

Backup Superblock:
long method:
$ dumpe2fs /dev/nvme0n1p# | grep superblock

short method:
$ mke2fs -n /dev/nvme0n1p#

Seems Ext2fsb 0.69 when used with "new ext4"
damages the checksum of Magic Number,
corrupts the Superblock,
and changes UUID or something.

ext4 drive becomes useless in Linux, No boot, nothing.
BUT still visible Ok in Windows with old ext2fsd.sys driver 0.69

as soon as i change the driver tp 0.70, partition becomes useless "damaged/empty" like Linux.

i think, it was a bad move from Linux developers,
to update ext4 filesystem, and leave the same name.
New ext4 should have been named ext5.
Ext2fsb 0.69 should have Not opened ext5.

this is absurd.
incompatible file system with same name.

**Comment by bobranten** [comment]
Yes it is unfortunate that older versions of the driver can corrupt a newer ext4 file system. Please only use version 0.70 of the driver when you have restored you're system.
