### ISSUE TITLE
error when detecting file systems and corruption of the drive when mounting it

### ISSUE THREAD

**Issue by juanro49** [bobranten/Ext4Fsd#14]
Hi!

I have the problem that when I open the manager, it does not detect correctly the file system (it should be ext4) and also it does not detect correctly the size. The worst thing is that when I try to map a drive, the file system of that drive is corrupted, so I have to reformat it.

![imagen](https://user-images.githubusercontent.com/11600804/130825939-e9514817-8fdd-433a-91bc-c679a8029034.png)

**Comment by Jai-JAP** [comment]
I too had the same issue but got it solved by entering the following commands in a administrator command prompt
```
bcdedit /set testsigning on
bcdedit /set nointegritychecks on
```

and reboot

**Comment by ouyen** [comment]
> I too had the same issue but got it solved by entering the following commands in a administrator command prompt
> 
> ```
> bcdedit /set testsigning on
> bcdedit /set nointegritychecks on
> ```
> 
> and reboot

not fix for me , maybe because I'm using win11(21H2)?

**Comment by ouyen** [comment]
after a system reinstall,it works for me,thx! ( win11 21H2 22000.318)
