### ISSUE TITLE
Does not seem to write Ext4 filesystem

### ISSUE THREAD

**Issue by robiwano** [bobranten/Ext4Fsd#17]
I have an SD card with Raspbian on it, ext4. I can read the files and it looks like I can write, the file gets changed. But if I remove and reinsert the SD card, nothing has really changed. Is there a way to flush changes to the SD card?

**Comment by Jai-JAP** [comment]
I also have the same issue on windows and ubuntu dualboot system

**Comment by robiwano** [comment]
On Windows, in the Ext2Fsd settings, you can right click on the drive letter and choose "Flush cache" (or similar). That fixed this for me.

**Comment by Jai-JAP** [comment]
Thanks this fixed the issue for me.
