### ISSUE TITLE
X64?

### ISSUE THREAD

**Issue by hacker1024** [bobranten/Ext4Fsd#2]
Is there a reason the solution's configured to build for x86 by default?
When setting to X64, the build fails, because it looks for a built `Ext2Srv.exe` in `..\Ext2Srv\Release\X86` instead of `..\Ext2Srv\Release\X64`.

**Comment by bobranten** [comment]
On Thu, 11 Jun 2020, hacker1024 wrote:

> When setting to X64, the build fails, because it looks for a built `Ext2Srv.exe` in `..\Ext2Srv\Release\X86` instead of `..\Ext2Srv\Release\X64`.

Thank you for this bug report. I have now corrected the project files so 
that the 32-bit Ext2Mgr is dependent on the 32-bit Ext2Srv and the 64-bit 
Ext2Mgr is dependent on the 64-bit Ext2Srv.

Bo Brantén
