### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by kristibektashi** [bobranten/Ext4Fsd#21]
There doesn't seem to have been any changes since March. Is this project still active or not?

**Comment by bobranten** [comment]
The project is still active. The reason there is low activity is because 
the driver itself works well for most users. What is needed most is to 
sign the driver and also a better installation program so more users can 
start using the driver.

Bo Branten

**Comment by kristibektashi** [comment]
> The project is still active. The reason there is low activity is because the driver itself works well for most users. What is needed most is to sign the driver and also a better installation program so more users can start using the driver. Bo Branten

How is signing the driver going? Because I need to use it on a system with Secure Boot and I don't want to enable testsigning

**Comment by Anonymous941** [comment]
I don't think it's necessary to sign it, people shouldn't have to pay in order to let users install something.

**Comment by kristibektashi** [comment]
> I don't think it's necessary to sign it, people shouldn't have to pay in order to let users install something on their own computers.

Unsigned drivers don't properly work with Secure Boot

**Comment by Anonymous941** [comment]
> > I don't think it's necessary to sign it, people shouldn't have to pay in order to let users install something on their own computers.
> 
> Unsigned drivers don't properly work with Secure Boot

It's still unfair and open-source developers shouldn't have to pay companies when the make a driver

**Comment by birdie-github** [comment]
You should get in touch with https://github.com/sandboxie-plus/Sandboxie who probably could sign (and build) the driver for you.

**Comment by bobranten** [comment]
we have now got help to sign the driver
