### ISSUE TITLE
A Question and a Request.

### ISSUE THREAD

**Issue by Mukul1127** [bobranten/Ext4Fsd#26]
Hello I have a question and a eequest.

Can you make a Github Action to build and when will the driver be signed?

**Comment by OLuserGi** [comment]
Hello!
I want install my Windows 11 for test into EXT4 base partition or into vDISK.vhdx, which save into EXT4 base partition.
I do this:
1) HDD 120GB = 2 GB FAT16 + 109,6 GB EXT4 base partition;
2) Save vDISK.vhdx 100 GB NTFS to 109,6 GB EXT4 base partition;
3) Save bootmgr.efi into 2 GB FAT16;
I need 4) mount EXT4 base partition (driver ext4_x64.efi or other ext4-driver for wondows bootmgr.efi) over BCD and bootmgr.efi;
5) Mount vDISK.vhdx 100 GB NTFS over BCD and bootmgr.efi;
6) Install Windows to vDISK.vhdx.

Now I have work OS Windows 11 on vDISK.vhdx into NTFS base partition. This work. I want use EXT4 base partition.

Can you help me?
