### ISSUE TITLE
Doesn't seem to be detecting the filesystem correctly

### ISSUE THREAD

**Issue by TheSpartaPT** [bobranten/Ext4Fsd#27]
I've tested your pre-built binaries on an sd card I know has an EXT4 partition, it incorrectly detected it as an EXT3 partition, and wouldn't mount the partition correctly.

I tested it with the old ext2fsd v0.69 and it worked correctly.

I wish I could give you a more detailed description of the problem, does this create any log files?

**Comment by bobranten** [comment]
Try the latest driver and also the updated manager.
