### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by kristibektashi** [bobranten/Ext4Fsd#29]
There haven't been any new commits since March of last year

**Comment by HexEvee** [comment]
is it?

**Comment by bobranten** [comment]
No, its not dead, the reason there has been no updates for a year is that 
it works fine on Win10 however there are reports of problems on Win11, I 
should try to investigate them and se if I can help. Win11 support and 
signining is the two major issues right now.

Bo Branten

**Comment by CodeCubeNeo** [comment]
Awesome!

**Comment by CodeCubeNeo** [comment]
Maybe add the .exe to the releases section and the site page http://www.acc.umu.se/~bosse in the About section (since http://www.ext2fsd.com/ is dead)? Would really appreciate it.

**Comment by bobranten** [comment]
We have fixed some bugs, signed the driver and published release 0.71 so I close this thread.
