### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by hmtheboy154** [bobranten/Ext4Fsd#3]
Hello, I just tried this new Ext4Fsd and it work really well. It's the first version of this software that can read my EXT4 drive without corrupt or anything.
But the thing is, I saw in the page you said that b2 should be installed on Windows 10 while I am using Windows 8.1 and it can install just fine. Is there something wrong here or you don't know that it can run ?

**Comment by bobranten** [comment]
On Fri, 14 Aug 2020, Huy Minh wrote:

> But the thing is, I saw in the page you said that b2 should be installed on Windows 10 while I am using Windows 8.1 and it can install just fine. Is there something wrong here or you don't know that it can run ?

Nice to here that it works!

As you have noted it can be installed on Windows 8 also so the other 
version is only for xp to win 7. It is safe to use the b2 version on 
Windows 8.

Bo Brantén

**Comment by hmtheboy154** [comment]
Thanks for the clarification. Hope you can keep up with this good work :D .
