### ISSUE TITLE
Where is .exe file or setup file so the program can install ?

### ISSUE THREAD

**Issue by george-martinec** [bobranten/Ext4Fsd#30]
How to install ?

**Comment by bobranten** [comment]
https://www.accum.se/~bosse/ext2fsd/0.70/Ext2Fsd-0.70b3w10-setup.exe
https://www.accum.se/~bosse/

Bo Branten

**Comment by Shadowphoenix** [comment]
for anyone else landing here: 
![grafik](https://github.com/bobranten/Ext4Fsd/assets/38107036/b2403e5b-2ddb-4494-a1c6-455b70dee306)

**Comment by bobranten** [comment]
The latest release is 0.71 and it is both on my homepage https://www.accum.se/~bosse/ and on the release tab on GitHub.
