### ISSUE TITLE
Use the driver on a daily basis.

### ISSUE THREAD

**Issue by its-mrarsikk** [bobranten/Ext4Fsd#32]
Hello. I have a dualboot of Windows and Ubuntu on my machine, and I often need to access the Ubuntu partition from Windows. But this driver requires test mode. There are a few problems: I don't like the Test mode message, and this feels insecure. Is there a way to use this on a daily basis, but without all those insecure settings?

**Comment by bobranten** [comment]
Sorry but to load the driver easy we need to "sign" the driver, we are 
investigating the possibillity to do that.

Also in adition to test mode I think you can allow loading unsigned 
drivers for the next boot by setting an boot parameter at reboot.

Bo Branten

**Comment by brian6932** [comment]
Any update on this?
A public pfx or cer file would go a long way, OpenZFS and WinBTFS have this.
