### ISSUE TITLE
Native Windows Support

### ISSUE THREAD

**Issue by ajmeese7** [bobranten/Ext4Fsd#33]
Hey, I just found this project today and it works perfectly for the use case I was going for! Great work maintaining this, and obviously props to the original creator @matt-wu.

Out of curiosity, do you know why this hasn't been picked up for official native Windows support yet? I know it's a fairly niche use case, but I can't think of any downsides to adding in `ext` partition support, since the driver already exists and having it picked up formally would allow them to flesh it out as they see fit and maybe solve the few existing problems the community has identified.

If you don't know, I could try reaching out to some friends in the industry to see if they can get a more concrete answer, this just seems like a huge missed opportunity on their part IMO. Cheers!

**Comment by bobranten** [comment]
Thank you for this report, it is always nice to here from users!

Bo Branten

**Comment by xAffan** [comment]
> Hey, I just found this project today and it works perfectly for the use case I was going for! Great work maintaining this, and obviously props to the original creator @matt-wu.
> 
> Out of curiosity, do you know why this hasn't been picked up for official native Windows support yet? I know it's a fairly niche use case, but I can't think of any downsides to adding in `ext` partition support, since the driver already exists and having it picked up formally would allow them to flesh it out as they see fit and maybe solve the few existing problems the community has identified.
> 
> If you don't know, I could try reaching out to some friends in the industry to see if they can get a more concrete answer, this just seems like a huge missed opportunity on their part IMO. Cheers!

Did you get an answer?

**Comment by ajmeese7** [comment]
@xAffan no updates on my end

**Comment by mirh** [comment]
Windows just supports FAT*, NTFS, UDF and (maybe) ReFS. 
I don't know why you think microsoft would be interested into supporting stuff that isn't "native to their own perspective". 
(even though they do eventually [support](https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk) ext4 with WSL2)

**Comment by ajmeese7** [comment]
@mirh exactly like you said, because Microsoft has pivoted towards Linux support/integration over the last several years, and I anticipate they will continue to do so moving forwards. After acquiring GitHub, the company has taken great steps to support the Open Source community, and I think this is a direction they will remain on as long as the current CEO remains in the chair :)

**Comment by OLuserGi** [comment]
Hello!
I want install my Windows 11 for test into EXT4 base partition or into vDISK.vhdx, which save into EXT4 base partition.
I do this:

HDD 120GB = 2 GB FAT16 + 109,6 GB EXT4 base partition;
Save vDISK.vhdx 100 GB NTFS to 109,6 GB EXT4 base partition;
Save bootmgr.efi into 2 GB FAT16;
I need 4) mount EXT4 base partition (driver ext4_x64.efi) over BCD and bootmgr.efi;
Mount vDISK.vhdx 100 GB NTFS over BCD and bootmgr.efi;
Install Windows to vDISK.vhdx.
Now I have work OS Windows 11 on vDISK.vhdx into NTFS base partition. This work. I want use EXT4 base partition.

Can you help me?

**Comment by mirh** [comment]
Don't you also have to [mod winload](https://github.com/maharmstone/quibble) to be able to load new file system drivers?
