### ISSUE TITLE
compile new version

### ISSUE THREAD

**Issue by SteavenGamerYT** [bobranten/Ext4Fsd#36]
please compile new version for us, lastest is 2021, 0.70b3, while you have updated the code to 2023, please compile new version

**Comment by Ast3risk-ops** [comment]
You can also just compile the project yourself with Visual Studio 2019.

**Comment by bobranten** [comment]
On Thu, 28 Sep 2023, SteavenGamerYT wrote:

> please compile new version for us, lastest is 2021, 0.70b3, while you have updated the code to 2023, please compile new version

Why is there a need to only recompile?

Bo Branten

**Comment by Ast3risk-ops** [comment]
> On Thu, 28 Sep 2023, SteavenGamerYT wrote: please compile new version for us, lastest is 2021, 0.70b3, while you have updated the code to 2023, please compile new version
> Why is there a need to only recompile? Bo Branten

Because the latest version on accum is from 2021 and there are commits from later years, must not have been enough for a new version.

**Comment by SteavenGamerYT** [comment]
I have tons of issues on the old version please update it

**Comment by githubmyname** [comment]
Where can I download the latest version in 2023?

**Comment by Ast3risk-ops** [comment]
> Where can I download the latest version in 2023?

There are no binaries, build the driver yourself using Visual Studio. Or use the old prebuilt binaries.

Also saying "in 2023" makes no difference, I wish people would stop adding that to messages and video titles.

**Comment by BrycensRanch** [comment]
this appears to be fixed considering there's a new github release with the precompiled binaries

**Comment by bobranten** [comment]
Yes we have fixed some bugs and also finally managed to sign the driver, the latest release is 0.71 so I close this thread now.
