### ISSUE TITLE
sudden power failure of the ext4 system disk cause restart fail？

### ISSUE THREAD

**Issue by eminhuang123** [bobranten/Ext4Fsd#4]
I’m using Ext4fsd filesystem driver(v0.70) which be installed on Win10 64bit.
But I found that sudden power failure of the ext4 system disk during operation, will cause restart fail.
I think, it could corrupt system important data. Ext4fsd need support commit and replay for journal that might be able to resolve this issue.
Unfortunately, I didn't find the journal commit function, only replay.

Looking forward to your follow-up Ext4fsd code update plan. Have you considered adding a journal commit? 
Or give me some advise for transplant from linux ext4?
Thanks.

**Comment by bobranten** [comment]
Thank you for this information. I will try to investigate it.

Bo Branten

**Comment by eminhuang123** [comment]
Thanks for your reply，Bo Branten.
Currently, I'm trying to append journal commit ported from linux ext4. 
But it is more difficult to transplant and debug jbd code. In order to adapt to the window driver, the original linux ext4 code implementation needs to be revised, but the effect is not what I want.
Have some good suggestions in this regard?

Emin Huang

**Comment by bobranten** [comment]
I have now checked in a bug fix for the checksum in the JBD2 journal 
superblock.

Bo Branten

**Comment by bobranten** [comment]
Hello,

with my latest bug fix handling power failures seem to work. Could you 
explain in more detail what commit code is missing?

Bo Branten

**Comment by eminhuang123** [comment]
Unfortunately, with your latest bug fix for the checksum still cannot solve this issue.

Emin Huang

**Comment by eminhuang123** [comment]
But there will be no power failure in the NTFS partition system disk.
As far as I know, ext4 and ntfs are journaling file system, including journal commit，replay，revoke function.

Refer to the journal commit code process in linux ext4, as follows: 
jbd2_journal_load ( fs\jdb2\journal.c ) -> journal_reset -> jbd2_journal_start_thread -> kjournald2 -> jbd2_journal_commit_transaction ( fs\jdb2\commit.c )
But the kjournald2 service is not found in the Ext4fsd project, I'm trying to transplant it.

Emin Huang
