### ISSUE TITLE
Report incorrect used space

### ISSUE THREAD

**Issue by fang1121cs** [bobranten/Ext4Fsd#44]
incorrect used size, cannot write files larger than 1.18 GiB
![Screenshot 2024-03-23 192627](https://github.com/bobranten/Ext4Fsd/assets/53415960/c7df65ae-dd74-484f-987d-ab80042b02e6)
![Screenshot 2024-03-23 192647](https://github.com/bobranten/Ext4Fsd/assets/53415960/79d34678-d8d1-4d4a-8022-165cd255becf)

actual used size, mounting from the router
![Screenshot 2024-03-23 193113](https://github.com/bobranten/Ext4Fsd/assets/53415960/ae8b1a5f-7e53-40e1-ade7-f6f7d845fb42)

**Comment by fang1121cs** [comment]
fallocate and delete could solve it

**Comment by hifron** [comment]
or improper right for media usage, router harrassment on demand, law in question in various countries

proper solution is to use wide accepted exfat filesystem, but some ecosystem rights need to be pay to use fat filesystem, android as example

fat is now much quicker, but requirements to use ntfs could bring security implications in restricted environments so ntfs could not be needed or wanted, mapping ntfs with restrictions is not now possible, autoplay also on demand... -> with shadowing and other fine examples of ntfs features, now in ReFS in NTFS space, not only on servers and data centre incoming fire, router says in media space ecosystem, undeveloped nature of router or consumer space, IT COMs waiting for nature of tabletoids..., and policies to be made, even on china...

some bug could be only land to be covered..., in proper oriented space..., devices coming but it could be wait time for some rights to be implicated or nature be or not be...

**Comment by hifron** [comment]
note: https://github.com/bobranten/Ext4Fsd/issues/70
