### ISSUE TITLE
Great tool. Thank you all

### ISSUE THREAD

**Issue by rain2307** [bobranten/Ext4Fsd#45]
感谢

**Comment by HebaruSan** [comment]
Hi @bobranten 🦸, I also wanted to thank you for reviving Ext4Fsd and providing builds that work on modern systems!

I thought it was dead and my only option to read files from my other partition would be a reboot, but here it is, installed quickly and working perfectly! If you had a donation link on your user profile, I'd tip a modest sum in gratitude. Cheers!

**Comment by bobranten** [comment]
Thank you for youre comment! It is great to hear from happy users!

Bo Branten
