### ISSUE TITLE
Windows XP can't use ext2mgr

### ISSUE THREAD

**Issue by jonm58** [bobranten/Ext4Fsd#48]
sorry,I'm just ask why?
![image](https://github.com/bobranten/Ext4Fsd/assets/73036321/ac2528a1-f601-4744-a591-e49155f1e5e4)

**Comment by bobranten** [comment]
That was weird, the oldest system I have access to test on is Vista. Here 
is another copy of the program you can try:
https://www.accum.se/~bosse/Ext2Mgr.exe
you can try it and tell me how it went.

Bo Branten

**Comment by jonm58** [comment]
> That was weird, the oldest system I have access to test on is Vista. Here is another copy of the program you can try: https://www.accum.se/~bosse/Ext2Mgr.exe you can try it and tell me how it went. Bo Branten

working,also find bug maybe is Ext4Fsd's "mfc42.dll" and "msvcrt.dll"
"GPT" is recognized as "Baisc" lol
![image](https://github.com/bobranten/Ext4Fsd/assets/73036321/0e6d1122-891c-49a1-ae94-9be29e13e90f)
![image](https://github.com/bobranten/Ext4Fsd/assets/73036321/79c0047c-ec25-4580-9e4f-1b3e889067ea)

**Comment by bobranten** [comment]
Just so I understand: The Ext2Mgr that is installed with
Ext2Fsd-0.71-setup-xp.exe
did not work for you but the new one did? Then I need to investigate that 
install program...

Bo Branten

**Comment by jonm58** [comment]
> Just so I understand: The Ext2Mgr that is installed with Ext2Fsd-0.71-setup-xp.exe did not work for you but the new one did? Then I need to investigate that install program... Bo Branten

The new Ext2Mgr does not work when having "mfc42.dll" and "msvcrt.dll" of Ext2Fsd-0.71-setup-xp.exe
The new Ext2Mgr can be used when there is no "mfc42.dll" and "msvcrt.dll" of Ext2Fsd-0.71-setup-xp.exe

**Comment by jonm58** [comment]
> Just so I understand: The Ext2Mgr that is installed with Ext2Fsd-0.71-setup-xp.exe did not work for you but the new one did? Then I need to investigate that install program... Bo Branten

Can you try this dll file? There is no problem with this dll on my WinXP
[mfc42.zip](https://github.com/bobranten/Ext4Fsd/files/14972102/mfc42.zip)

**Comment by vertaa** [comment]
When I try to mount my 4tb external drive. I get a crash.

![image](https://github.com/bobranten/Ext4Fsd/assets/67488797/1a2d7bfd-8863-403f-955e-0ed68bb2d391)

**Comment by bobranten** [comment]
Some of you have already solved this by yourself but I have now updated the installation program for XP with a dll that should work on both XP and Vista: https://www.accum.se/~bosse/ext2fsd/0.71/Ext2Fsd-0.71-setup-xp.exe
