### ISSUE TITLE
Windows Defender blocking installer

### ISSUE THREAD

**Issue by jamcole** [bobranten/Ext4Fsd#6]
Just a heads up, Windows Defender is marking http://www.acc.umu.se/~bosse/ext2fsd/0.70/Ext2Fsd-0.70b3w10-setup.exe as malicious ( Trojan:Win32/Zpevdo.B ) - Apparently a pretty common problem so they have a way to report false positives that you may want to look into.

**Comment by bobranten** [comment]
I have now reported it as a false detection to Microsoft so hopefully they 
will unlist it soon.

Bo Branten
