### ISSUE TITLE
Windows cannot access the drive mounted with Ext2Fsd. Error: Location is not available.

### ISSUE THREAD

**Issue by annadapb** [bobranten/Ext4Fsd#9]
On Windows 10 20H2 build 19042.928, after mounting a ext4 drive, when I try to open the drive from My Computer, it says that I need to format the disk. On Linux, the disk has no error and I've checked it using `fsck`.

When I press 'Cancel' to not format the drive, following error happens,

```
Location is not available

F:\ is not accessible.

The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted. 
```

**Comment by rikka0w0** [comment]
Confirmed, does not work in win10 20H2. In addition, in the config window, it says "the service could not be started", even if I manually click the start button.

**Comment by bobranten** [comment]
This error message is typical if the driver has not been loaded, make sure you have allowed test signed drivers to load with the command "bcdedit /set testsigning on".
